In [134]:
#test split using RandomForestClassifier 
import pandas as pd 
data = pd.read_csv('diabetics.csv') 
# print(data.shape) 
# print(data.head) 
# x=data.drop("outcome", axis=1) 
# y=data['outcome']
x = data_set.iloc[:, :-1 ]
y = data_set.iloc[:, 19]
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3) 
# print(data['outcome'].describe()) 
#print(data.ndim) 
from sklearn.ensemble import RandomForestClassifier 
from sklearn import svm 
clf = svm.SVC(kernel='linear')
rf = RandomForestClassifier(n_estimators = 10) 
clf.fit(x_train,y_train) 

y_pred=clf.predict(x_test) 

from sklearn.metrics import confusion_matrix 
conf=confusion_matrix(y_pred,y_test) 
from sklearn import metrics 
print('confusion matrix',conf) 
print(' Accurcy',metrics.accuracy_score(y_pred,y_test)) 
print('preciction',metrics.precision_score(y_pred,y_test)) 
print('f1 score',metrics.f1_score(y_pred,y_test)) 
print('recall',metrics.recall_score(y_pred,y_test))

confusion matrix [[140  61]
 [ 28 117]]
 Accurcy 0.7427745664739884
preciction 0.6573033707865169
f1 score 0.7244582043343653
recall 0.8068965517241379

In [128]:
data_set

,a,b,c,d,e,f,g,h,I,j,k,l,m,n,o,p,q,r,s,outcome
0,1,1,22,22,22,19,18,14,49.895756,17.775994,5.270920,0.771761,0.018632,0.006864,0.003923,0.003923,0.486903,0.100025,1,0
1,1,1,24,24,22,18,16,13,57.709936,23.799994,3.325423,0.234185,0.003903,0.003903,0.003903,0.003903,0.520908,0.144414,0,0
2,1,1,62,60,59,54,47,33,55.831441,27.993933,12.687485,4.852282,1.393889,0.373252,0.041817,0.007744,0.530904,0.128548,0,1
3,1,1,55,53,53,50,43,31,40.467228,18.445954,9.118901,3.079428,0.840261,0.272434,0.007653,0.001531,0.483284,0.114790,0,0
4,1,1,44,44,44,41,39,27,18.026254,8.570709,0.410381,0.000000,0.000000,0.000000,0.000000,0.000000,0.475935,0.123572,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,1,1,34,34,34,33,31,24,6.071765,0.937472,0.031145,0.003115,0.000000,0.000000,0.000000,0.000000,0.537470,0.116795,0,0
1147,1,1,49,49,49,49,45,37,63.197145,27.377668,8.067688,0.979548,0.001552,0.000000,0.000000,0.000000,0.516733,0.124190,0,0
1148,1,0,49,48,48,45,43,33,30.461898,13.966980,1.763305,0.137858,0.011221,0.000000,0.000000,0.000000,0.560632,0.129843,0,0
1149,1,1,39,36,29,23,13,7,40.525739,12.604947,4.740919,1.077570,0.563518,0.326860,0.239568,0.174584,0.485972,0.106690,1,1
1150,1,1,7,7,7,7,7,5,69.423565,7.031843,1.750548,0.046597,0.021180,0.008472,0.000000,0.000000,0.556192,0.088957,0,0